In [42]:
import pandas as pd

In [2]:
len(dir(pd))

141

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [43]:
import numpy as np
a = np.array([10,20,30,40,50])
b = pd.Series(a)
print(b)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [44]:
a = np.array([10,20,50,90,40])
b = pd.Series(a,index = ['r1','r2','r3','r4','r5'])

b

r1    10
r2    20
r3    50
r4    90
r5    40
dtype: int64

In [45]:
b['r1']

np.int64(10)

In [6]:
b[2]

/tmp/ipython-input-2083252473.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b[2]

np.int64(50)

above it is showing warning but i dont want this warning will use ignore

In [46]:
import warnings
warnings.filterwarnings('ignore')

In [47]:
b[2]

np.int64(50)

##DataFrame

In [48]:
a = {
    'Name':['John','Peter','Steve','Brad','Smith','Hasan'],
     'Location':['USA','UK','CANADA','INDIA','PARIS','DUBAI'],
     'Age':[20,21,25,29,32,34],
     'Company':['Google','Meta','IBM','MSFT','Wipro','Delloite'],
     'Salary':[1200,1400,1500,1900,2400,4500,]
     }
b = pd.DataFrame(a)

b

    Name Location  Age   Company  Salary
0   John      USA   20    Google    1200
1  Peter       UK   21      Meta    1400
2  Steve   CANADA   25       IBM    1500
3   Brad    INDIA   29      MSFT    1900
4  Smith    PARIS   32     Wipro    2400
5  Hasan    DUBAI   34  Delloite    4500

In [49]:
b = pd.DataFrame(a,index=['r1','r2','r3','r4','r5','r6'])
b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    INDIA   29      MSFT    1900
r5  Smith    PARIS   32     Wipro    2400
r6  Hasan    DUBAI   34  Delloite    4500

In [50]:
b['Company']['r3']

'IBM'

In [51]:
b['Age']['r5']

np.int64(32)

In [14]:
b['Company']['r6']

'Delloite'

In [52]:
b['Location']['r5'] = 'China'

b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    INDIA   29      MSFT    1900
r5  Smith    China   32     Wipro    2400
r6  Hasan    DUBAI   34  Delloite    4500

In [53]:
b.shape

(6, 5)

In [54]:
b.size

30

If i want to access the group of values will use

loc
iloc

syntax : [Rs:Re , Cs:Ce]

loc will not use n-1 and no index and iloc will use n-1 and index

In [55]:
b.loc['r2':'r4','Location':'Company']

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    INDIA   29    MSFT

In [56]:
b.loc['r3':'r4','Name':'Company']

     Name Location  Age Company
r3  Steve   CANADA   25     IBM
r4   Brad    INDIA   29    MSFT

In [57]:
b.iloc[1:4,1:4]

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    INDIA   29    MSFT

In [58]:
b.iloc[2:4,0:4]

     Name Location  Age Company
r3  Steve   CANADA   25     IBM
r4   Brad    INDIA   29    MSFT

In [59]:
b.loc['r2':'r5','Location':'Company']

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    INDIA   29    MSFT
r5    China   32   Wipro

In [60]:
b.iloc[1:5,1:4]

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    INDIA   29    MSFT
r5    China   32   Wipro

If i want to access only columns

In [61]:
b.iloc[ : ,1:3]

   Location  Age
r1      USA   20
r2       UK   21
r3   CANADA   25
r4    INDIA   29
r5    China   32
r6    DUBAI   34

Only Column names

In [62]:
b.columns

Index(['Name', 'Location', 'Age', 'Company', 'Salary'], dtype='object')

Only Row names

In [63]:
b.index

Index(['r1', 'r2', 'r3', 'r4', 'r5', 'r6'], dtype='object')

In [64]:
b['Age']

r1    20
r2    21
r3    25
r4    29
r5    32
r6    34
Name: Age, dtype: int64

In the excel sheet if i have the same column it will override

In [65]:
b['Age'] = [1,2,3,4,5,6]

b

     Name Location  Age   Company  Salary
r1   John      USA    1    Google    1200
r2  Peter       UK    2      Meta    1400
r3  Steve   CANADA    3       IBM    1500
r4   Brad    INDIA    4      MSFT    1900
r5  Smith    China    5     Wipro    2400
r6  Hasan    DUBAI    6  Delloite    4500

if the column is not there it will create

In [66]:
b['Tax'] = [10,20,30,40,50,60]

In [67]:
b

     Name Location  Age   Company  Salary  Tax
r1   John      USA    1    Google    1200   10
r2  Peter       UK    2      Meta    1400   20
r3  Steve   CANADA    3       IBM    1500   30
r4   Brad    INDIA    4      MSFT    1900   40
r5  Smith    China    5     Wipro    2400   50
r6  Hasan    DUBAI    6  Delloite    4500   60

In [68]:
b['TDS'] = [150,160,np.nan,200,np.nan,250]
b

     Name Location  Age   Company  Salary  Tax    TDS
r1   John      USA    1    Google    1200   10  150.0
r2  Peter       UK    2      Meta    1400   20  160.0
r3  Steve   CANADA    3       IBM    1500   30    NaN
r4   Brad    INDIA    4      MSFT    1900   40  200.0
r5  Smith    China    5     Wipro    2400   50    NaN
r6  Hasan    DUBAI    6  Delloite    4500   60  250.0

In [36]:
b = b.dropna()

In [37]:
b

     Name Location  Age   Company  Salary  Tax    TDS
r1   John      USA    1    Google    1200   10  150.0
r2  Peter       UK    2      Meta    1400   20  160.0
r4   Brad    INDIA    4      MSFT    1900   40  200.0
r6  Hasan    DUBAI    6  Delloite    4500   60  250.0

In [69]:
b['TDS'] = b['TDS'].fillna(120)

b

     Name Location  Age   Company  Salary  Tax    TDS
r1   John      USA    1    Google    1200   10  150.0
r2  Peter       UK    2      Meta    1400   20  160.0
r3  Steve   CANADA    3       IBM    1500   30  120.0
r4   Brad    INDIA    4      MSFT    1900   40  200.0
r5  Smith    China    5     Wipro    2400   50  120.0
r6  Hasan    DUBAI    6  Delloite    4500   60  250.0



##axis = 1(column)
##axis = 0(row)

In [70]:
b = b.drop(['Age'],axis = 1)
b

     Name Location   Company  Salary  Tax    TDS
r1   John      USA    Google    1200   10  150.0
r2  Peter       UK      Meta    1400   20  160.0
r3  Steve   CANADA       IBM    1500   30  120.0
r4   Brad    INDIA      MSFT    1900   40  200.0
r5  Smith    China     Wipro    2400   50  120.0
r6  Hasan    DUBAI  Delloite    4500   60  250.0

In [71]:
b = b.rename(columns = {'Tax':'Income_Tax'})
b

     Name Location   Company  Salary  Income_Tax    TDS
r1   John      USA    Google    1200          10  150.0
r2  Peter       UK      Meta    1400          20  160.0
r3  Steve   CANADA       IBM    1500          30  120.0
r4   Brad    INDIA      MSFT    1900          40  200.0
r5  Smith    China     Wipro    2400          50  120.0
r6  Hasan    DUBAI  Delloite    4500          60  250.0

In [72]:
b.to_csv('own_data.csv',index = False)

In [76]:
df = pd.read_csv('/content/Titanic1.csv')
df

   CustomerID     Name  Age      City  PurchaseAmount
0         101    Alice   25  New York          250.50
1         102      Bob   30    London          340.75
2         103  Charlie   35     Paris          120.00
3         104    David   28    Berlin          560.20
4         105      Eva   40     Tokyo          430.00

In [77]:
df.columns

Index(['CustomerID', 'Name', 'Age', 'City', 'PurchaseAmount'], dtype='object')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5 non-null      int64
 1   Name            5 non-null      object
 2   Age             5 non-null      int64
 3   City            5 non-null      object
 4   PurchaseAmount  5 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [82]:
df.isnull().sum()

CustomerID        0
Name              0
Age               0
City              0
PurchaseAmount    0
dtype: int64

In [83]:
df['City'].unique()

array(['New York', 'London', 'Paris', 'Berlin', 'Tokyo'], dtype=object)

In [84]:
df['City'].value_counts()

City
New York    1
London      1
Paris       1
Berlin      1
Tokyo       1
Name: count, dtype: int64

In [85]:
df.head()

   CustomerID     Name  Age      City  PurchaseAmount
0         101    Alice   25  New York          250.50
1         102      Bob   30    London          340.75
2         103  Charlie   35     Paris          120.00
3         104    David   28    Berlin          560.20
4         105      Eva   40     Tokyo          430.00

In [86]:
df.tail()

   CustomerID     Name  Age      City  PurchaseAmount
0         101    Alice   25  New York          250.50
1         102      Bob   30    London          340.75
2         103  Charlie   35     Paris          120.00
3         104    David   28    Berlin          560.20
4         105      Eva   40     Tokyo          430.00

In [87]:
df.sample(3)

   CustomerID   Name  Age    City  PurchaseAmount
1         102    Bob   30  London          340.75
4         105    Eva   40   Tokyo          430.00
3         104  David   28  Berlin          560.20

In [88]:
df.to_csv('Titanic_cleaned_data.csv',index=False)